import Button from "@/app/_components/button";
import Input from "@/app/_components/input";
import { create_families_service } from "@/app/services/families-service";
import { Plus, User, Home, MapPin, Hash, Users, Search } from "lucide-react";
import moment from "moment";
import React, { useState, useEffect } from "react";
import { useForm } from "react-hook-form";
import Swal from "sweetalert2";
import axios from "axios";

export default function CreateFamSection({ onClose }) {
    const {
        register,
        handleSubmit,
        reset,
        watch,
        setValue,
        formState: { errors, isSubmitting },
    } = useForm({
        defaultValues: {
            familyNumber: "",
            isAutoGenerated: true,
            headOfFamily: "",
            isExistingResident: true,
            zone: "",
            street: "",
            houseNumber: "",
            ownershipType: "",
        },
    });

    const isAutoGenerated = watch("isAutoGenerated");
    const isExistingResident = watch("isExistingResident");
    const selectedZone = watch("zone");

    // Resident search states
    const [residents, setResidents] = useState([]);
    const [searchQuery, setSearchQuery] = useState("");
    const [showResidentDropdown, setShowResidentDropdown] = useState(false);
    const [selectedResident, setSelectedResident] = useState(null);

    // Zone and street data for Barangay 2
    const zoneStreets = {
        "Don Juan Subdivision": [
            "Don Juan Street",
            "Rosario Street",
            "San Pedro Street",
            "Santo Niño Street",
        ],
        "Don Juan Extension": [
            "Extension Road",
            "Main Street",
            "Side Street",
            "Corner Street",
        ],
        Margarita: [
            "Margarita Main Road",
            "Sampaguita Street",
            "Orchid Street",
            "Rose Street",
        ],
        Mondragon: [
            "Mondragon Avenue",
            "Lopez Street",
            "Santos Street",
            "Reyes Street",
        ],
        Caballero: [
            "Caballero Street",
            "Pioneer Street",
            "Heritage Street",
            "Unity Street",
        ],
        Mansfield: [
            "Mansfield Road",
            "Oak Street",
            "Pine Street",
            "Maple Street",
        ],
        "San Julio": [
            "San Julio Street",
            "Rizal Avenue",
            "Bonifacio Street",
            "Mabini Street",
        ],
        "Teachers Village": [
            "Education Avenue",
            "Scholar Street",
            "Academy Road",
            "Campus Drive",
        ],
        Bulangan: [
            "Bulangan Main Road",
            "River Street",
            "Bridge Road",
            "Waterside Street",
        ],
        Sumakwel: [
            "Sumakwel Avenue",
            "Tribal Street",
            "Heritage Road",
            "Cultural Street",
        ],
    };

    const zones = Object.keys(zoneStreets);
    const availableStreets = selectedZone ? zoneStreets[selectedZone] : [];

    // Generate family number
    const generateFamilyNumber = () => "FAM-" + moment().format("MMDDYYHHmmss");

    // Reset street when zone changes
    useEffect(() => {
        if (selectedZone) {
            setValue("street", "");
        }
    }, [selectedZone, setValue]);

    // Fetch residents when search query changes
    useEffect(() => {
        const fetchResidents = async () => {
            if (searchQuery.length > 0) {
                try {
                    const response = await axios.get("/api/barangay_residents");
                    const allResidents = response.data.data || response.data;

                    // Filter residents based on search query
                    const filtered = allResidents.filter((resident) => {
                        const fullName = `${resident.firstName || ""} ${
                            resident.middleName || ""
                        } ${resident.lastName || ""}`.toLowerCase();
                        return fullName.includes(searchQuery.toLowerCase());
                    });

                    setResidents(filtered);
                    setShowResidentDropdown(true);
                } catch (error) {
                    console.error("Error fetching residents:", error);
                }
            } else {
                setResidents([]);
                setShowResidentDropdown(false);
            }
        };

        const debounceTimer = setTimeout(fetchResidents, 300);
        return () => clearTimeout(debounceTimer);
    }, [searchQuery]);

    const handleResidentSelect = (resident) => {
        const fullName = `${resident.firstName} ${resident.middleName || ""} ${
            resident.lastName
        }`.trim();
        setSelectedResident(resident);
        setSearchQuery(fullName);
        setValue("headOfFamily", fullName);
        setShowResidentDropdown(false);
    };

    const submitForm = async (data) => {
        try {
            if (data.isAutoGenerated) {
                data.familyNumber = generateFamilyNumber();
            }
            await create_families_service(data);
            await Swal.fire({
                icon: "success",
                title: "Family saved successfully",
                showConfirmButton: false,
                timer: 1500,
            });
            reset();
            setSearchQuery("");
            setSelectedResident(null);
            onClose && onClose();
        } catch (error) {
            console.error("Error saving family:", error);
            Swal.fire({
                icon: "error",
                title: "Something went wrong",
                text: "Please try again later",
            });
        }
    };

    const ownershipTypes = [
        "Owned",
        "Rented",
        "Government Housing",
        "Caretaker",
        "Sharing/Boarding",
        "Others",
    ];

    return (
        <form
            onSubmit={handleSubmit(submitForm)}
            className="max-w-7xl mx-auto space-y-6"
        >
            {/* Family Number Section */}
            <div>
                <label className="block text-sm font-medium text-gray-700 mb-3">
                    Family/Household Number *
                </label>
                <div className="space-y-3">
                    <div className="flex items-center gap-3">
                        <input
                            type="checkbox"
                            {...register("isAutoGenerated")}
                            checked={isAutoGenerated}
                            onChange={(e) => {
                                setValue("isAutoGenerated", e.target.checked);
                                if (e.target.checked) {
                                    setValue(
                                        "familyNumber",
                                        generateFamilyNumber(),
                                    );
                                } else {
                                    setValue("familyNumber", "");
                                }
                            }}
                            className="w-4 h-4 text-green-600 border-gray-300 rounded focus:ring-green-500"
                        />
                        <label
                            htmlFor="autoGenerate"
                            className="text-sm text-gray-700"
                        >
                            Auto-generate family number
                        </label>
                    </div>

                    <Input
                        register={register("familyNumber", {
                            required: "Field is required",
                        })}
                        error={errors?.familyNumber?.message}
                        label="Family/Household Number"
                        name="familyNumber"
                        disabled={isAutoGenerated}
                        iconLeft={<Hash className="w-4 h-4" />}
                        readOnly={isAutoGenerated}
                    />
                </div>
            </div>

            {/* Head of Family */}
            <div>
                <label className="block text-sm font-medium text-gray-700 mb-3">
                    <User className="inline w-4 h-4 mr-1" />
                    Head of Family *
                </label>

                <div className="space-y-3">
                    <div className="flex gap-4">
                        <label className="flex items-center">
                            <input
                                type="radio"
                                value={true}
                                {...register("isExistingResident")}
                                checked={isExistingResident === true}
                                onChange={() => {
                                    setValue("isExistingResident", true);
                                    setValue("headOfFamily", "");
                                    setSearchQuery("");
                                    setSelectedResident(null);
                                }}
                                className="w-4 h-4 text-green-600 border-gray-300"
                            />
                            <span className="ml-2 text-sm text-gray-700">
                                Select from residents
                            </span>
                        </label>

                        <label className="flex items-center">
                            <input
                                type="radio"
                                value={false}
                                {...register("isExistingResident")}
                                checked={isExistingResident === false}
                                onChange={() => {
                                    setValue("isExistingResident", false);
                                    setValue("headOfFamily", "");
                                    setSearchQuery("");
                                    setSelectedResident(null);
                                }}
                                className="w-4 h-4 text-green-600 border-gray-300"
                            />
                            <span className="ml-2 text-sm text-gray-700">
                                Manual input
                            </span>
                        </label>
                    </div>

                    {isExistingResident ? (
                        <div className="relative w-full">
                            <div className="relative">
                                <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400 w-5 h-5 z-10" />
                                <input
                                    type="text"
                                    value={searchQuery}
                                    onChange={(e) => {
                                        setSearchQuery(e.target.value);
                                        setValue(
                                            "headOfFamily",
                                            e.target.value,
                                        );
                                    }}
                                    onFocus={() => {
                                        if (residents.length > 0) {
                                            setShowResidentDropdown(true);
                                        }
                                    }}
                                    placeholder="Search resident by name..."
                                    className="w-full pl-11 pr-4 py-2.5 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500 focus:border-transparent"
                                />
                            </div>

                            {/* Dropdown Results */}
                            {showResidentDropdown && residents.length > 0 && (
                                <div className="absolute z-20 w-full mt-1 bg-white border border-gray-300 rounded-lg shadow-lg max-h-60 overflow-y-auto">
                                    {residents.map((resident) => (
                                        <button
                                            key={resident.id}
                                            type="button"
                                            onClick={() =>
                                                handleResidentSelect(resident)
                                            }
                                            className="w-full text-left px-4 py-3 hover:bg-gray-50 border-b border-gray-100 last:border-b-0 transition-colors"
                                        >
                                            <div className="flex items-center gap-3">
                                                <div className="flex-shrink-0 w-10 h-10 bg-green-100 rounded-full flex items-center justify-center">
                                                    <User className="w-5 h-5 text-green-600" />
                                                </div>
                                                <div className="flex-1 min-w-0">
                                                    <p className="font-medium text-gray-900 truncate">
                                                        {resident.firstName}{" "}
                                                        {resident.middleName ||
                                                            ""}{" "}
                                                        {resident.lastName}
                                                    </p>
                                                    <p className="text-sm text-gray-500 truncate">
                                                        Age:{" "}
                                                        {resident.age || "N/A"}{" "}
                                                        •{" "}
                                                        {resident.sex || "N/A"}
                                                    </p>
                                                </div>
                                            </div>
                                        </button>
                                    ))}
                                </div>
                            )}

                            {/* No results message */}
                            {showResidentDropdown &&
                                searchQuery.length > 0 &&
                                residents.length === 0 && (
                                    <div className="absolute z-20 w-full mt-1 bg-white border border-gray-300 rounded-lg shadow-lg p-4">
                                        <p className="text-sm text-gray-500 text-center">
                                            No residents found. Try a different
                                            search or use manual input.
                                        </p>
                                    </div>
                                )}

                            {errors.headOfFamily && (
                                <p className="text-sm text-red-500 mt-1 ml-1">
                                    {errors.headOfFamily.message}
                                </p>
                            )}

                            {/* Selected Resident Info */}
                            {selectedResident && (
                                <div className="mt-2 p-3 bg-green-50 border border-green-200 rounded-lg">
                                    <p className="text-sm text-green-800">
                                        <strong>Selected:</strong>{" "}
                                        {selectedResident.firstName}{" "}
                                        {selectedResident.middleName || ""}{" "}
                                        {selectedResident.lastName}
                                        {selectedResident.age && (
                                            <span>
                                                {" "}
                                                • Age: {selectedResident.age}
                                            </span>
                                        )}
                                    </p>
                                </div>
                            )}

                            {/* Hidden input for form validation */}
                            <input
                                type="hidden"
                                {...register("headOfFamily", {
                                    required: "Head of family is required",
                                })}
                            />
                        </div>
                    ) : (
                        <Input
                            label="Head of Family Name"
                            register={register("headOfFamily", {
                                required: "Head of family is required",
                            })}
                            name="headOfFamily"
                            iconLeft={<User className="w-4 h-4" />}
                            error={errors?.headOfFamily?.message}
                        />
                    )}
                </div>
            </div>

            {/* Address Section */}
            <div>
                <label className="block text-sm font-medium text-gray-700 mb-3">
                    <MapPin className="inline w-4 h-4 mr-1" />
                    Address *
                </label>

                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                    {/* Zone Dropdown */}
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">
                            Zone *
                        </label>
                        <div className="relative">
                            <MapPin className="absolute left-2 top-1/2 -translate-y-1/2 text-gray-500 w-4 h-4 z-10" />
                            <select
                                {...register("zone", {
                                    required: "Zone is required",
                                })}
                                className="w-full pl-10 pr-4 py-2.5 border border-gray-300 bg-white rounded-md focus:ring-2 focus:ring-green-500 focus:border-transparent"
                            >
                                <option value="">Select Zone</option>
                                {zones.map((zone) => (
                                    <option key={zone} value={zone}>
                                        {zone}
                                    </option>
                                ))}
                            </select>
                        </div>
                        {errors.zone && (
                            <p className="text-sm text-red-500 mt-1 ml-1">
                                {errors.zone.message}
                            </p>
                        )}
                    </div>

                    {/* Street Dropdown */}
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">
                            Street *
                        </label>
                        <select
                            {...register("street", {
                                required: "Street is required",
                            })}
                            disabled={!selectedZone}
                            className="w-full px-4 py-2.5 border border-gray-300 bg-white rounded-md focus:ring-2 focus:ring-green-500 focus:border-transparent disabled:bg-gray-100 disabled:cursor-not-allowed"
                        >
                            <option value="">
                                {selectedZone
                                    ? "Select Street"
                                    : "Select Zone First"}
                            </option>
                            {availableStreets.map((street) => (
                                <option key={street} value={street}>
                                    {street}
                                </option>
                            ))}
                        </select>
                        {errors.street && (
                            <p className="text-sm text-red-500 mt-1 ml-1">
                                {errors.street.message}
                            </p>
                        )}
                    </div>
                    <div className="mt-6">
                        <Input
                          
                            register={register("houseNumber", {
                                required: "House number is required",
                            })}
                            error={errors?.houseNumber?.message}
                            label="House Number"
                            name="houseNumber"
                            placeholder="e.g., 123"
                        />
                    </div>
                </div>
            </div>

            {/* Ownership */}
            <div>
                <label className="block text-sm font-medium text-gray-700 mb-3">
                    <Home className="inline w-4 h-4 mr-1" />
                    Ownership Type *
                </label>
                <div className="relative">
                    <Home className="absolute left-2 top-1/2 -translate-y-1/2 text-gray-500 w-4 h-4 z-10" />
                    <select
                        {...register("ownershipType", {
                            required: "Ownership type is required",
                        })}
                        className="w-full pl-10 pr-4 py-2.5 border border-gray-300 bg-white rounded-md focus:ring-2 focus:ring-green-500 focus:border-transparent"
                    >
                        <option value="">Select ownership type</option>
                        {ownershipTypes.map((type) => (
                            <option key={type} value={type}>
                                {type}
                            </option>
                        ))}
                    </select>
                    {errors.ownershipType && (
                        <p className="text-sm text-red-500 mt-1 ml-1">
                            {errors.ownershipType.message}
                        </p>
                    )}
                </div>
            </div>

            {/* Submit */}
            <div className="pt-4 border-t border-gray-200">
                <Button
                    disabled={isSubmitting}
                    type="submit"
                    variant="primary"
                    size="lg"
                    className="w-full"
                >
                    <Plus className="w-5 h-5 mr-2" />
                    {isSubmitting ? "Saving..." : "Create New Family"}
                </Button>
            </div>
        </form>
    );
}
