<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Families extends Model
{
    protected $fillable = [
        'familyNumber',
        'isAutoGenerated',
        'headOfFamily',
        'isExistingResident',
        'sitio',
        'street',
        'houseNumber',
        'ownershipType',
    ];

    public function members()
    {
        return $this->hasMany(FamilyMember::class, 'family_id');
    }

    public function household()
    {
        return $this->hasOne(Household::class, 'familyId');
    }
}
